### ISSUE TITLE
Design Doc Checklist

### ISSUE THREAD

**Issue by KevinHJo** [tkoh13/Interest#1]
# Wiki Page Home
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [ ] all links route the correct page
## Comments
- Create the wiki pages for all design docs and have links in both the table of contents and on the right

---
# MVP List
- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points
## Comments
-  'Profile' refers to the profile page, User auth is a separate MVP that will come beforehand
- Need to add User Auth and Production README
- Put the descriptions of the MVPs in bullet points underneath each one
---
